name: "CI / CD"
on:
  push:
    branches:
      - live
      - develop
jobs:
  setup:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          repository: br-data/cloud-deploy-action
          token: ${{ secrets.BRDATA_ACCESS }}
          path: ./
      - id: build-and-deploy
        name: Build and Deploy
        uses: ./
        with:
          access_token: ${{ secrets.BRDATA_ACCESS }}
          repo_name: ${{ github.event.repository.name }}
          tag: ${{ github.sha }}
          branch: ${{ github.ref }}
          basic_auth: ${{ secrets.BASIC_PW }}
          gpg_key: ${{ secrets.GPG_ACTION_PASSPHRASE }}
